### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by evolvedlight** [lastbackend/lastbackend#139]
##### Description
I cloned the repo and followed the instructions. They don't work as there's no makefile in cmd/daemon

##### Version
Latest from git

##### How To Reproduce
1. Try to follow your installion instructions from the wiki

**Comment by undassa** [comment]
Hi @evolvedlight. Yeah, will changing in a week with deployments scripts.

**Comment by vinayakkulkarni** [comment]
This area can be improved upon by adding documentation here: https://github.com/lastbackend/lastbackend/wiki

**Comment by undassa** [comment]
@vinayakkulkarni agreed. We started to move documentation to open-source, but not completed yet.
We'll fix that soon.

**Comment by gernest** [comment]
After fixing the make file. Now the instructions should work.

Something that you should be aware of ,  installing with make works only with os x and linux

If you are in os x or linux. After cloning just run `make`

**Comment by toonsevrin** [comment]
I would also like to see more extensive installation instructions. Like whether or not kubernetes should be active and configured, how the configuration of new nodes works...

**Comment by cihann** [comment]
hi,

btw, one of the dependencies link is not correct. repo's link should be github.com/cenkalti/backoff

https://github.com/lastbackend/lastbackend/blob/master/Godeps/Godeps.json#L49

**Comment by poonai** [comment]
while i'm trying vagrant up. it showing me build error!!

**Comment by undassa** [comment]
@sch00lb0y I'll check it tomorrow. Maybe something was changed.
@cihann - @unloop will see tomorrow. It's strange cause travis-ci builds are all successful.

**Comment by kamikazechaser** [comment]
Debian Jessie after `make deps` Im getting what looks like an certification fail

```bash
echo "Pre-building configuration"
Pre-building configuration
mkdir -p build/linux && mkdir -p build/darwin
echo "Building Last.Backend daemon"
Building Last.Backend daemon
GOOS=linux  go build -ldflags "-X main.Version=0.1.0" -o build/linux/lastbackend cmd/daemon/daemon.go
# golang.org/x/net/context/ctxhttp
../../../golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)
# golang.org/x/oauth2/jws
../../../golang.org/x/oauth2/jws/jws.go:75: undefined: base64.RawURLEncoding
../../../golang.org/x/oauth2/jws/jws.go:93: undefined: base64.RawURLEncoding
../../../golang.org/x/oauth2/jws/jws.go:113: undefined: base64.RawURLEncoding
../../../golang.org/x/oauth2/jws/jws.go:124: undefined: base64.RawURLEncoding
../../../golang.org/x/oauth2/jws/jws.go:151: undefined: base64.RawURLEncoding
../../../golang.org/x/oauth2/jws/jws.go:174: undefined: base64.RawURLEncoding
# golang.org/x/net/http2
../../../golang.org/x/net/http2/transport.go:216: req.Cancel undefined (type *http.Request has no field or method Cancel)
../../../golang.org/x/net/http2/transport.go:220: req.Cancel undefined (type *http.Request has no field or method Cancel)
../../../golang.org/x/net/http2/transport.go:792: req.Cancel undefined (type *http.Request has no field or method Cancel)
# k8s.io/client-go/1.5/pkg/util/cert
../../../k8s.io/client-go/1.5/pkg/util/cert/cert.go:76: key.Public undefined (type *rsa.PrivateKey has no field or method Public)
../../../k8s.io/client-go/1.5/pkg/util/cert/cert.go:103: key.Public undefined (type *rsa.PrivateKey has no field or method Public)
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by AdhityaRamadhanus** [comment]
@kamikazechaser What's your go version? try update to 1.6/1.7

**Comment by kamikazechaser** [comment]
@AdhityaRamadhanus Thanks, updating fixed it!

**Comment by nemirlev** [comment]
Nothing changes((( Can't install.

**Comment by undassa** [comment]
Our team is now forced to release our cloud version in next 2 weeks.
I'll try to refresh documentation and instructions in next few days.

It will fix issues with vagrant.. I have almost complete all ansible instructions and azure template deployment script for kubernetes with last.backend deployment.

**Comment by nemirlev** [comment]
@undassa Do you can say how i can install now?)))
or me waiting few days for do this?

**Comment by undassa** [comment]
@bigcrowd 
fisrt off all you need to install kubernetes
after it you need to run rethinkdb

to install lastbackend daemon from sources you need to clone it and execute make build.
and to finish - change config.yml (pass valid config to connect to kubernetes and rethink) - and thats all..

The hardest operation is to install kubernetes - and last.backend just a go package.. In next week I hope I'll finish automatic installation scripts.

**Comment by undassa** [comment]
For now, Last.Backend platform does not need kubernetes installed in system.
Only docker needs to be ready.
```
make run
```

So we need to update our docs. See #309 to additional information
