### ISSUE TITLE
Site typo

### ISSUE THREAD

**Issue by toonsevrin** [lastbackend/lastbackend#143]
There's a little type [here](https://lastbackend.com/about/). I assume you mean experience.

**Comment by toonsevrin** [comment]
It should be "We are improving development experience through innovative products"

**Comment by undassa** [comment]
@toonsevrin Thx. Yeah. We'll deploy fixed version today! If you'll find more mistakes, I would like to fix it quickly!

**Comment by toonsevrin** [comment]
Will do. Am I allowed to ask questions with issues, or would you rather have me send emails for that?
(I'm quite eager to get started with this)

**Comment by undassa** [comment]
@toonsevrin As you wish. I'll setup slack in few days. But you can email me undassa@lastbackend.com or entire team team@lastbackend.com. Thx for help)

**Comment by undassa** [comment]
BTW, we have public website repo [here](https://github.com/lastbackend/website)

**Comment by toonsevrin** [comment]
Great, I'll use gh issues that way other people can follow the conversation as well.

**Comment by undassa** [comment]
@toonsevrin perfect

**Comment by undassa** [comment]
updated and deployed

**Comment by toonsevrin** [comment]
still a little typo: it should be through instead of trough :)

**Comment by undassa** [comment]
@toonsevrin done )
