### ISSUE TITLE
Easy datastore management?

### ISSUE THREAD

**Issue by toonsevrin** [lastbackend/lastbackend#144]
##### Description
Not sure if it's integrated already but it would be great if lastbackend also provides a quick way to setup **highly available** datastores (mongo, redis, postgres, rabbitmq...). A system like [flynn.io](flynn.io) has would work.

It's essential for our apps to save data to a persistent store, and this store must be highly available. The system I am hoping for is one with automatic high availability (maybe 1 sync slave, 1 async slave), monitoring and automatic reprovisioning (when a node is permanently down, append a new slave), data security and eventually sharding.

**Comment by undassa** [comment]
@toonsevrin Agreed. We're preparing special templates for that. This is in process right now.
First will be mongo cluster, redid cluster, postgres cluster. After that will be elk, rabbit and others. 
But if you need some kind of these up faster, we'll changing priorities.

I think I'll need to add this in our doc.

**Comment by toonsevrin** [comment]
Yep, once this is properly integrated I recommend it being on the landing page. The priorities are perfect. Is  cluster recovery (when a node permanently dies) a planned feature of these templates?

**Comment by undassa** [comment]
@toonsevrin I think it critical feature, cause we need to provide HA clusters.

**Comment by toonsevrin** [comment]
I couldn't agree more, I'd be happy to take a look at the design documents/templates once they are in place.

**Comment by undassa** [comment]
I'll attach link to them in this conversation

**Comment by undassa** [comment]
Since we've come back to actively opensource supporting, we are ready to close this issue.
We have persistent volumes support in or design map. I'll attach PR and instruction how to use datastores.

**Comment by undassa** [comment]
now it's possible with persistent volumes
