### ISSUE TITLE
IRC inactive

### ISSUE THREAD

**Issue by toonsevrin** [lastbackend/lastbackend#152]
It appears like the IRC is currently not actively used. I believe the developers should either be active on it for us to discuss the project with them.

**Comment by undassa** [comment]
@toonsevrin I'll create a slack room for us, where we can chat and discuss about all.

**Comment by undassa** [comment]
Removed IRC and changed it to Slack.
On main repo page there is a badge to join our slack community.
Will happy to see you and others.
