### ISSUE TITLE
vagrant test box provision failed

### ISSUE THREAD

**Issue by xinity** [lastbackend/lastbackend#157]
##### Description
While running vagrant up, i have this strange error message:
==> default: Step 9 : ADD ../.. /go/src/github.com/lastbackend/lastbackend
==> default: Forbidden path outside the build context: ../.. ()
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

##### Version
[`$ deploy version`]

##### How To Reproduce
1. vagrant up

any idea what went wrong ?

**Comment by undassa** [comment]
@xinity Dockerfile contains wrong ADD instruction cause it can not add sources in parent directories.
Will fix tomorrow.

**Comment by maestrofx** [comment]
Yes, I got this error too:

> ==> default: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/core/lastbackend/images: no such file or directory
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> docker build -t lastbackend -f /home/core/lastbackend/images/lastbackend/Dockerfile /home/core/lastbackend
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/core/lastbackend/images: no such file or directory

**Comment by undassa** [comment]
related to #139
close this
