### ISSUE TITLE
Custom http status texte replacing with go idiomatic http status texte ?

### ISSUE THREAD

**Issue by donutloop** [lastbackend/lastbackend#164]
Hey,

i have discovered in the sub pacakge (libs/errors/errors.go) several custom http status texte.
The Golang std lib has all standard http status texte in "net/http/status.go" and helper functions.

Can i replace all unnecessary custom status texte with std status texte and refactor the unique texte ?  

Best regards,

Marcel

**Comment by undassa** [comment]
@donutloop Hi Marcel. Yeah, you are right. It will be great.
