### ISSUE TITLE
nothing happen "vagrant up"

### ISSUE THREAD

**Issue by maestrofx** [lastbackend/lastbackend#167]
##### Description
Nothing happen after executing `vagrant up`

##### Version
[`$ deploy version`]

##### How To Reproduce
1. I tried to clone and directly run the Vagrantfile, fix the NFS problem first in my local environment
2. All package were downloaded and provisioned and bring the node up
3. try to SSH, enter the node, but no `lastbackend` command.

##### Optional information
netstat results:

---

> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2025/hyperkube      
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      788/etcd2           
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      788/etcd2           
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      797/kubelet         
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      2098/hyperkube      
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      788/etcd2           
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      788/etcd2           
tcp6       0      0 :::10255                :::*                    LISTEN      797/kubelet         
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd           
tcp6       0      0 :::443                  :::*                    LISTEN      2025/hyperkube      
tcp6       0      0 :::4194                 :::*                    LISTEN      797/kubelet         
tcp6       0      0 :::10250                :::*                    LISTEN      797/kubelet         
tcp6       0      0 :::10251                :::*                    LISTEN      1973/hyperkube      
tcp6       0      0 :::10252                :::*                    LISTEN      2074/hyperkube      
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:935             0.0.0.0:*                           -                   
udp        0      0 10.0.2.15:68            0.0.0.0:*                           1432/systemd-networ 
udp6       0      0 fe80::582c:2fff:fe9:546 :::*                                1432/systemd-networ 
udp6       0      0 fe80::a00:27ff:fece:546 :::*                                1432/systemd-networ 

any help, please!
Thank you.

**Comment by undassa** [comment]
related to #139 
close this
