### ISSUE TITLE
Update Last.Backend installation doc

### ISSUE THREAD

**Issue by undassa** [lastbackend/lastbackend#309]
##### Update Last.Backend installation doc
After major changes, we need to update our doc with actual info.
Need to create articles about

- [x] deploy docker-machine
- [x] deploy from dockerfile
- [x] build and deploy from sources

##### Version
v0.9.0

**Comment by sourcec0de** [comment]
@undassa do you guys have plans for providing instructions for installation on kubernetes?

**Comment by undassa** [comment]
@sourcec0de I'm not sure you need to use lastbackend with kubernetes, course it has the same functions.

**Comment by undassa** [comment]
https://docs.lastbackend.com/#_create_local_development_environment
