### ISSUE TITLE
More detailed prerequisited installation

### ISSUE THREAD

**Issue by pbajno** [lastbackend/lastbackend#332]
I'm new at go, but trying to do sth.
I've installed latest go 1.8.3 and it works, but which next requisites do you mean?
Could you provide at least link so i can find them?

Is go etcd client for v3, this: https://github.com/coreos/etcd/tree/master/clientv3 ?

And what about go docker?

I tried to install go etcd client for v3 but got this error:
work/src/github.com/coreos/etcd/clientv3/client.go:236: dialer.DialContext undefined (type *net.Dialer has no field or method DialContext)

and made it this far.

At this point you have this, which does not provide sufficient information for a noob like me:
1.1.1. Prerequisites
Go 1.7 or higher
Go docker client v17.03
Go etcd client for v3

**Comment by undassa** [comment]
We'll update all installation instructions on next week.
For this version - all is on active development stage, so I'll close this.
On next week we should complete it.
