### ISSUE TITLE
Building not successful.

### ISSUE THREAD

**Issue by Castafers** [lastbackend/lastbackend#342]
##### Description
I can't install LastBackend.

##### Version
Latest, unsure what version.

##### Optional information

root@frozola:~# go get github.com/lastbackend/lastbackend
package github.com/lastbackend/lastbackend: no buildable Go source files in /root/work/src/github.com/lastbackend/lastbackend

**Comment by kirillDanshin** [comment]
try `go get -v github.com/lastbackend/lastbackend/... && pushd $GOPATH/github.com/lastbackend/lastbackend; make deps && make build && make install; popd`
