### ISSUE TITLE
Ansible Installation

### ISSUE THREAD

**Issue by randy-girard** [lastbackend/lastbackend#538]
##### Description
I was looking at running the self hosted version of this, but there doesn't appear to be the ansible installation instructions. Are these not completed yet or just missing?

##### Version
[`$ lb version`]

**Comment by undassa** [comment]
Hi @randy-girard, thanks for the issue. We're almost completed our new release with all docs you need. I will close this after it will be done

**Comment by masterofmonkeys** [comment]
Hi, any update on the ansible  instruction on how to install it locally ?

**Comment by undassa** [comment]
Hey! @muconsulting 
We are close with new release with ansible installation roles included.

**Comment by zeroryuki** [comment]
any update on this?
